---
title: "Using `omxr`"
author: "Greg Macfarlane"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_caption: TRUE
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup}
set.seed(10)
```



```{r load_library}
library(omxr)
```


# Create and write.

`.omx` files are HDF5 containers storing many different matrices and their
attributes. You can create a new container with the `create_omx` command.

```{r create_omx}
zones <- 1:10
create_omx(
  file = "simple.omx",  
  numrows = length(zones), numcols = length(zones)
)
```

Let's start with a 10-zone system with random trips and costs.

```{r make_matrix}
trips <- matrix(rnorm(n = length(zones)^2, 200, 50),  
                nrow = length(zones), ncol = length(zones))
cost <- matrix(rlnorm(n = length(zones)^2, 1, 1),
               nrow = length(zones), ncol = length(zones))
```

We can store these in the omx container.

```{r write_omx}
write_omx(file = "simple.omx", matrix = trips, "trips", 
          description = "Total Trips")

write_omx(file = "simple.omx", matrix = cost, "cost", 
          description = "Generalized Cost")
```


# Read

# Lookups

